jobs:
  build:
    runs triggered by a pull request from a forked repository.

### How to Fix:
1. **Ensure Permissions**: Make sure-on: ubuntu-latest
    permissions:
      contents: write  # Ensure this permission is set

    steps:
 the workflow has the `contents: write` permission for the job. This permission is necessary for submitting dependency    - uses: actions/checkout@v4
    - name: Set up J graphs.
2. **Modify Workflow for Forks**: Adjust the workflow to handle pull requests from forks. You can add a condition to skip the dependency submissionDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: ' step if the event is a pull request from a fork.

Here is an example of how you can update thetemurin'

    - name: Make gradlew executable
      run: workflow to conditionally skip the dependency submission chmod +x ./gradlew

<<<<<<< HEAD
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed:
=======

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
    # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
    #
    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    #   with:
    #     gradle-version: '8.9'
    #
    # - name: Build with Gradle 8.9
    #   run: gradle build

  dependency-submission:
>>>>>>> parent of 7317c94 (Merge pull request #3 from CampusTycoon/testing-CI)

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Cache Gradle dependencies
      uses: actions/cache@    - uses: actions/checkout@v4
    - name: Setv3
      with:
        path: |
          ~/.gradle/c up JDK 17
      uses: actions/setup-java@v4
     aches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', with:
        java-version: '17'
        distribution: '**/gradle-wrapper.properties') }}
        restore- 'temurin'

    - name: Make gradlew executable
      runkeys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle Wrapper
      run: ./gradlew: chmod +x ./gradlew

    - name: Cache Gradle dependencies build

    - name: Generate and submit dependency graph
      if: github.event_name != 'pull_request'
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle # Skip this step for pull requests from forks
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
